---@class CS.F_MODULE_STATE : CS.System.Enum
CS.F_MODULE_STATE = {}

---@field public CS.F_MODULE_STATE.value__ : CS.System.Int32
CS.F_MODULE_STATE.value__ = nil

---@field public CS.F_MODULE_STATE.PREPARE : CS.F_MODULE_STATE
CS.F_MODULE_STATE.PREPARE = nil

---@field public CS.F_MODULE_STATE.RUNNING : CS.F_MODULE_STATE
CS.F_MODULE_STATE.RUNNING = nil

---@field public CS.F_MODULE_STATE.PAUSE : CS.F_MODULE_STATE
CS.F_MODULE_STATE.PAUSE = nil

---@field public CS.F_MODULE_STATE.ENDED : CS.F_MODULE_STATE
CS.F_MODULE_STATE.ENDED = nil