#!/bin/sh
##version=1.0.4##

{ #try
	filename=".git/hooks/error.txt"
	declare -A myMap=()
	while read line || [[ -n ${line} ]]
	do
		r=${line%'#@#'*}
		myMap["$r"]=${line#*'#@#'}
	done < $filename
	while read local_ref local_sha remote_ref remote_sha
	do
		er="f"
		git diff $local_sha $remote_sha --name-only  | awk '//' > pushhooktmpfile
		echo "--------------开始执行资源推送检查--------------"
		while read line
		do
			v=${myMap[$line]}
			if [ -n "$v" ]
			then
				er="t"
				echo -n "资源检查未通过: "
				echo -n $line
				echo -n "=>"
				echo $v
			fi
		done < pushhooktmpfile
		rm -rf pushhooktmpfile

		echo "--------------资源推送检查执行完毕--------------"
		if [ "$er" != "f" ]
		then
		echo "-------------<<检查结果:禁止推送>>------------"
			echo ""
			echo ""
			exit 1
		fi
		echo "-------------<<检查结果:允许推送>>------------"
		echo ""
		echo ""
		exit 0
	done
} || { #catch
		echo "-------------<<推送监测脚本异常>>------------"
	exit 1
}